1.3.1 Задание

Задача:
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.
Решение:

In [1]:
import numpy as np

array = np.zeros((8, 8), dtype=int)
array[1::2, ::2] = 1
array[::2, 1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2 Задание

Задача:
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.
Решение:

In [2]:
import numpy as np

array = np.zeros((5, 5))
array += np.arange(5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


1.3.3 Задание

Задача:
Создать массив 3x3x3 со случайными значениями.
Решение:

In [3]:
import numpy as np

array = np.random.random((3, 3, 3))
print(array)

[[[0.18055588 0.83119617 0.69117548]
  [0.28295413 0.65091873 0.4510411 ]
  [0.79003846 0.35051559 0.55118701]]

 [[0.53692442 0.22721014 0.89131782]
  [0.74359691 0.96356555 0.28011347]
  [0.75915551 0.790441   0.55694061]]

 [[0.55370526 0.16396929 0.05939501]
  [0.25349574 0.81183742 0.93457212]
  [0.74935454 0.67204587 0.50850374]]]


1.3.4 Задание

Задача:
Создать матрицу с 0 внутри, и 1 на границах.
Решение:

In [4]:
import numpy as np

array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


1.3.5 Задание

Задача:
Создайте массив и отсортируйте его по убыванию.
Решение:

In [8]:
import numpy as np

array = np.random.randint(1, 10, 5)
array = sorted(array, reverse=True)
print(array)

[8, 5, 1, 1, 1]


1.3.6 Задание

Задача:
Создайте матрицу, выведите ее форму, размер и размерность.
Решение:

In [9]:
import numpy as np

array = np.arange(9).reshape(3, 3)
print(array)
print('Форма:', array.shape)
print('Размерность:', array.itemsize * array.size)
print('Размер:', array.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Форма: (3, 3)
Размерность: 36
Размер: (3, 3)


2.3.1 Задание

Задача:
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.
Решение:

In [10]:
import pandas as pd
import numpy as np

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([5, 4, 3, 2, 1])
distance = np.sqrt(sum(pow(a-b, 2) for a, b in zip(s1, s2)))
print(distance)

6.324555320336759


2.3.2 Задание

Задача:
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных
Решение:

In [11]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/diamonds.csv'
dataframe = pd.read_csv(url)
print(dataframe)

       carat        cut color clarity  depth  table     x     y     z  price
0       0.23      Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1       0.21    Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2       0.23       Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3       0.29    Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4       0.31       Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
53935   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50   2757
53936   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61   2757
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56   2757
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64   2757

[53940 rows x 10 columns]


2.3.3 Задание

Задача:
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.
Решение:

In [12]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/diamonds.csv'
dataframe = pd.read_csv(url)
print('Head:\n', dataframe.head(2))
print('Tail:\n', dataframe.tail(3))
print('Shape:\n', dataframe.shape)
print('Describe:\n', dataframe.describe())

print('Iloc:\n', dataframe.iloc[1:4])
print('Diamonds with color "E"\n', dataframe[dataframe['color'] == 'E'])

Head:
    carat      cut color clarity  depth  table     x     y     z  price
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
Tail:
        carat        cut color clarity  depth  table     x     y     z  price
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56   2757
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64   2757
Shape:
 (53940, 10)
Describe:
               carat         depth         table             x             y  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184      5.731157      5.734526   
std        0.474011      1.432621      2.234491      1.121761      1.142135   
min        0.200000     43.000000     43.000000      0.000000      0.000000   
25%        0.400000     61.000000     5

3.2.2 Задание

Задача:
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.
Решение:

In [14]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
print(dataframe)

scaler = MinMaxScaler()
dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
print(dataframe)

dataframe['sepal_width_cm'] = (dataframe['sepal_width_cm'] - dataframe['sepal_width_cm'].mean()) \
                              / dataframe['sepal_width_cm'].std()


print(dataframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 